version: '3.9'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite+aiosqlite:////data/labelcheck.db
      DEV_MODE: "true"
      DEV_USER_EMAIL: agent@ttb.gov
      SECRET_KEY: change-this-to-a-long-random-string
      STORAGE_BACKEND: local
      UPLOAD_DIR: /data/uploads
      TRANSFORMERS_OFFLINE: "1"
      HF_DATASETS_OFFLINE: "1"

    volumes:
      - app_data:/data

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  app_data:
